apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
  labels:
    pantalasa.org/argocd-template: standard-v2
  annotations:
    pantalasa.org/template-version: "2.0.0"
    pantalasa.org/owner: stephanie@pantalasa.org
spec:
  project: platform
  source:
    repoURL: https://github.com/pantalasa/spring-petclinic
    targetRevision: HEAD
    path: deploy/k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-petclinic-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
